### ISSUE TITLE
查询结果返回为json字符串，略为坑爹

### ISSUE THREAD

**Issue by slince** [linjinmin/Lemon#1]
1. 如果真需要为api考虑，那客户端会自己json serilalize；强制返回字符串反而失去了灵活性

2. 查询结果并不准

```php
Query:query('340321xxxxxxxx'); 
```
结果为：
```
string(25) "{"province":"","city":""}"
```

**Comment by slince** [comment]
Query在引入资源文件 使用的`require_once` 返回布尔值，所以导致全部失效；你最好先自己测试下，写个单元测试啥的

**Comment by slince** [comment]
推了一个PR [https://github.com/linjinmin/Lemon/pull/2](https://github.com/linjinmin/Lemon/pull/2)

**Comment by linjinmin** [comment]
客户端是会自动json serilalize么。。  以前的时候 都是json_encode 后返回给客户端使用， 谢谢了。 我看一下你推送的代码

**Comment by slince** [comment]
@linjinmin  那倒不是，我意思是开发者自己调用json_encode ; 这个只要返回数组就好；数组比字符串更有灵活性

**Comment by slince** [comment]
你得去点亮readme上面的图标，要不然太丑了；点击图标即可定位到服务平台，注册下账号服务即可点亮了；

**Comment by linjinmin** [comment]
好。  我明天晚上看看。。 今晚有点事情。 。谢谢指导。
